# Generated by Django 3.0.4 on 2021-01-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210105_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name', 'email', 'subject', 'comment', 'created_at')},
        ),
    ]
