# Generated by Django 3.1.4 on 2021-01-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210107_0653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('created_at', 'name', 'email', 'subject', 'comment')},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ('created_at', 'email')},
        ),
    ]
