# Generated by Django 3.1.6 on 2021-04-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210422_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_one',
            field=models.ImageField(upload_to='static/assets/img/portfolio-detail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_three',
            field=models.ImageField(upload_to='static/assets/img/portfolio-detail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_two',
            field=models.ImageField(upload_to='static/assets/img/portfolio-detail'),
        ),
    ]
