# Generated by Django 3.1.6 on 2021-04-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210422_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_three',
            field=models.ImageField(upload_to='static/assets/portfolio-detail'),
        ),
    ]
